parameters:
  movecloser.export_converter_bundle.user: 'admin'
  movecloser.export_converter_bundle.templates: [ ]
  movecloser.export_converter_bundle.attributes_map: [ ]
  movecloser.export_converter_bundle.currencies_map:
    default: 'PLN'

services:
  movecloser.export_converter_bundle.launcher.synchronous_job_launcher:
    class: MoveCloser\ExportConverterBundle\Launcher\LocalJobLauncher
    arguments:
      - '@akeneo_batch.job_repository'
      - '@akeneo_batch.job.job_registry'
      - '%movecloser.export_converter_bundle.user%'

  movecloser.export_converter_bundle.attributes:
    class: MoveCloser\ExportConverterBundle\Services\Attributes
    arguments:
      - '@kernel'
      - '%movecloser.export_converter_bundle.attributes_map%'

  movecloser.export_converter_bundle.languages:
    class: MoveCloser\ExportConverterBundle\Services\Locales
    arguments:
      - '%movecloser.export_converter_bundle.currencies_map%'

  movecloser.export_converter_bundle.converter:
    class: MoveCloser\ExportConverterBundle\Services\Converter
    arguments:
      - '%movecloser.export_converter_bundle.templates%'
      - '@movecloser.export_converter_bundle.attributes'
      - '@movecloser.export_converter_bundle.languages'

  movecloser.export_converter_bundle.xlsx_product_writer:
    class: MoveCloser\ExportConverterBundle\Enrichment\XlsxProductWriter
    arguments:
      - '@pim_connector.array_converter.standard_to_flat.product_localized'
      - '@pim_connector.factory.flat_item_buffer'
      - '@pim_connector.writer.file.product.flat_item_buffer_flusher'
      - '@pim_catalog.repository.attribute'
      - '@pim_connector.writer.file.media_exporter_path_generator'
      - '@akeneo.pim.enrichment.connector.write.file.flat.generate_headers_from_family_codes'
      - '@akeneo.pim.enrichment.connector.write.file.flat.generate_headers_from_attribute_codes'
      - '@pim_enrich.connector.flat_translators.product_translator'
      - '@akeneo_file_storage.repository.file_info'
      - '@akeneo_file_storage.file_storage.filesystem_provider'
      - [ 'pim_catalog_file', 'pim_catalog_image' ]

  movecloser.export_converter_bundle.step.convert_export_step:
    class: MoveCloser\ExportConverterBundle\Step\ConvertExportStep
    arguments:
      - 'export'
      - '@event_dispatcher'
      - '@akeneo_batch.job_repository'
      - '@pim_connector.reader.database.product'
      - '@pim_connector.processor.normalization.product'
      - '@movecloser.export_converter_bundle.xlsx_product_writer'
      - '@movecloser.export_converter_bundle.converter'
      - '%pim_job_product_batch_size%'
      - '@akeneo_batch.job.job_stopper'


